services:
  postgres-dev:
    image: postgres:latest
    container_name: MCS-Postgres-Dev

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mcs-dev

    ports:
      - 5432:5432

  postgres-test:
    image: postgres:latest
    container_name: MCS-Postgres-Test

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mcs-test

    ports:
      - 5431:5432